GET http://localhost:5000/getTimetable

###

POST http://localhost:5000/getMeal
Content-Type: application/json

{
    "date": "20210923"
}

###

POST http://localhost:5000/getSchedule
Content-Type: application/json

{
    "start_day": "20220220",
    "end_day": "20220402"
}

###

GET http://localhost:5000/getTimetable

###

POST http://localhost:5000/regTodo
Content-Type: application/json

{
    "analyze_mode": false,
    "content": "5/1 사회 수행평가 준비하기"
}

###

GET http://localhost:5000/getTodo

###

POST http://localhost:5000/api/session/register
Content-Type: application/json

{
    "id": "",
    "password": ""
}

###

POST http://localhost:5000/api/session/login
Content-Type: application/json

{
    "id": "",
    "password": ""
}

###

GET http://localhost:5000/api/session/auth