GET http://localhost:5000/getTimetable

###

POST http://localhost:5000/getMeal
Content-Type: application/json

{
    "date": "20210923"
}

###

POST http://localhost:5000/getSchedule
Content-Type: application/json

{
    "start_day": "20220220",
    "end_day": "20220402"
}

###

GET http://localhost:5000/getTimetable

###

POST http://localhost:5000/api/todo/regTodo
Content-Type: application/json

{
    "grade": "2",
    "group": "1",
    "desc": "aa"
}

###

POST http://localhost:5000/api/session/register
Content-Type: application/json

{
    "id": "",
    "password": ""
}

###

POST http://localhost:5000/api/session/login
Content-Type: application/json

{
    "id": "",
    "password": ""
}

###

GET http://localhost:5000/api/session/auth

###

POST http://localhost:5000/api/todo/getTodo
Content-Type: application/json

{
    "grade": "3",
    "group": "1"
}

###

POST http://localhost:5000/api/board/getBoard
Content-Type: application/json

{
    "arc": 0
}

###

POST http://localhost:5000/api/regBoard
Content-Type: application/json

{
    "div": "자유글",
    "title": "이겈",
    "uploader": "민뭉",
    "contents": "두근두근!"
}

###

POST http://localhost:5000/api/removeBoard
Content-Type: application/json

{
    "boardId": "ibpywyww6D"
}

###

POST http://localhost:5000/api/board/getArticle
Content-Type: application/json

{
    "href": "/Dk1TA6yc79"
}

###

POST http://localhost:5000/api/todo/removeTodo
Content-Type: application/json

{
    "grade": "3",
    "group": "1",
    "todoId": "1BzFbnZSbU"
}